export const kn = {
  app: { name: 'ತುಳಿರ್', tagline: 'ತ್ಯಾಜ್ಯಕ್ಕೂ ಮೀರಿದ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸುವುದು', subtitle: 'ತುಳಿರ್ ಇಂದು ಕೇವಲ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ ಮಾಡುತ್ತಿಲ್ಲ; ತ್ಯಾಜ್ಯವನ್ನು ಉಪಯುಕ್ತ ಸಂಪನ್ಮೂಲಗಳು, ಮೌಲ್ಯ ಮತ್ತು ಸುಸ್ಥಿರ ಅವಕಾಶಗಳಾಗಿ ಪರಿವರ್ತಿಸುವ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸುತ್ತಿದೆ.' },
  nav: { home: 'ಮುಖಪುಟ', howItWorks: 'ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', about: 'ಬಗ್ಗೆ', marketplace: 'ಮಾರುಕಟ್ಟೆ', login: 'ಲಾಗಿನ್', getStarted: 'ಪ್ರಾರಂಭಿಸಿ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', logout: 'ಲಾಗ್‌ಔಟ್', language: 'ಭಾಷೆ' },
  hero: { cta: 'ತ್ಯಾಜ್ಯ ಪಿಕಪ್ ವಿನಂತಿ', ctaSecondary: 'ಮಾರುಕಟ್ಟೆ ಅನ್ವೇಷಿಸಿ' },
  ecosystem: { title: 'ನಮ್ಮ ಪರಿಸರ ವ್ಯವಸ್ಥೆ', subtitle: 'ತ್ಯಾಜ್ಯದಿಂದ ಮೌಲ್ಯಕ್ಕೆ ಪೂರ್ಣ ವೃತ್ತಾಕಾರ ಪ್ರಯಾಣ', waste: 'ತ್ಯಾಜ್ಯ', collect: 'ಸಂಗ್ರಹಿಸಿ', verify: 'ಪರಿಶೀಲಿಸಿ', manufacture: 'ತಯಾರಿಸಿ', create: 'ರಚಿಸಿ', deliver: 'ವಿತರಿಸಿ', reuse: 'ಮರುಬಳಕೆ' },
  roles: { title: 'ಆರು ಸಂಪರ್ಕಿತ ಪಾತ್ರಗಳು', subtitle: 'ಪ್ರತಿ ಪಾತ್ರವೂ ವೃತ್ತಾಕಾರ ಆರ್ಥಿಕತೆಯಲ್ಲಿ ಪ್ರಮುಖ ಪಾತ್ರ ವಹಿಸುತ್ತದೆ', wasteGenerator: 'ತ್ಯಾಜ್ಯ ಉತ್ಪಾದಕ', collectionPartner: 'ಸಂಗ್ರಹಣೆ ಪಾಲುದಾರ', manufacturer: 'ತಯಾರಕ', consumer: 'ಗ್ರಾಹಕ', deliveryPartner: 'ವಿತರಣಾ ಪಾಲುದಾರ', admin: 'ನಿರ್ವಾಹಕ' },
  auth: { login: 'ಲಾಗಿನ್', signup: 'ಸೈನ್ ಅಪ್', email: 'ಇಮೇಲ್', password: 'ಪಾಸ್‌ವರ್ಡ್', confirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ', fullName: 'ಪೂರ್ಣ ಹೆಸರು', phone: 'ಫೋನ್ ಸಂಖ್ಯೆ', location: 'ಸ್ಥಳ', role: 'ಪಾತ್ರ', forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?', createAccount: 'ಖಾತೆ ರಚಿಸಿ', welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ', welcomeMessage: 'ನಿಮ್ಮ ತುಳಿರ್ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ' },
  waste: { createRequest: 'ತ್ಯಾಜ್ಯ ವಿನಂತಿ ರಚಿಸಿ', myRequests: 'ನನ್ನ ವಿನಂತಿಗಳು', wasteType: 'ತ್ಯಾಜ್ಯ ಪ್ರಕಾರ', weight: 'ತೂಕ (ಕೆಜಿ)', types: { organic: 'ಸಾವಯವ', foodWaste: 'ಆಹಾರ ತ್ಯಾಜ್ಯ', plastic: 'ಪ್ಲಾಸ್ಟಿಕ್', paper: 'ಕಾಗದ', cardboard: 'ಕಾರ್ಡ್‌ಬೋರ್ಡ್', glass: 'ಗಾಜು', metal: 'ಲೋಹ', eWaste: 'ಇ-ತ್ಯಾಜ್ಯ', mixed: 'ಮಿಶ್ರ', other: 'ಇತರ' }, weightMessage: 'ನಿಖರ ತೂಕ ಗೊತ್ತಿಲ್ಲವೇ? ಪರವಾಗಿಲ್ಲ. ನಮ್ಮ ಸಂಗ್ರಹಣೆ ಪಾಲುದಾರ ಪಿಕಪ್ ಸಮಯದಲ್ಲಿ ಪರಿಶೀಲಿಸುತ್ತಾರೆ.' },
  common: { loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', success: 'ಯಶಸ್ಸು!', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', delete: 'ಅಳಿಸಿ', edit: 'ತಿದ್ದಿ', view: 'ನೋಡಿ', submit: 'ಸಲ್ಲಿಸಿ', accept: 'ಸ್ವೀಕರಿಸಿ', reject: 'ತಿರಸ್ಕರಿಸಿ', confirm: 'ದೃಢೀಕರಿಸಿ', noData: 'ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ', back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', close: 'ಮುಚ್ಚಿ', locationUnavailable: 'ಸ್ಥಳ ಪ್ರವೇಶ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಸ್ಥಳ ಅನುಮತಿ ಸಕ್ರಿಯಗೊಳಿಸಿ.' },
  notifications: { title: 'ಅಧಿಸೂಚನೆಗಳು', markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಿದೆ ಎಂದು ಗುರುತಿಸಿ', noNotifications: 'ಇನ್ನೂ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ' },
  footer: { copyright: '© 2026 ತುಳಿರ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.' },
  finance: { earnings: 'ಆದಾಯ', payments: 'ಪಾವತಿಗಳು', payouts: 'ಪೇಔಟ್', totalEarnings: 'ಒಟ್ಟು ಆದಾಯ', pendingPayout: 'ಬಾಕಿ ಪೇಔಟ್', paidOut: 'ಪಾವತಿಸಲಾಗಿದೆ', commission: 'ಕಮಿಷನ್', platformCommission: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಕಮಿಷನ್', baseFee: 'ಮೂಲ ಶುಲ್ಕ', distanceCharge: 'ದೂರ ಶುಲ್ಕ', perKm: 'ಕಿ.ಮೀ-ಗೆ', totalPayable: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ', estimatedTotal: 'ಅಂದಾಜು ಒಟ್ಟು', wasteCharge: 'ತ್ಯಾಜ್ಯ ಶುಲ್ಕ', basePickup: 'ಮೂಲ ಪಿಕಪ್ ಶುಲ್ಕ', distanceByTransport: 'ಸಾರಿಗೆ ಲೆಕ್ಕಹಾಕುತ್ತದೆ', paymentId: 'ಪಾವತಿ ಐಡಿ', paymentStatus: 'ಪಾವತಿ ಸ್ಥಿತಿ', payoutStatus: 'ಪೇಔಟ್ ಸ್ಥಿತಿ', paid: 'ಪಾವತಿಸಲಾಗಿದೆ', pending: 'ಬಾಕಿ', rateCard: 'ದರ ಕಾರ್ಡ್', perBin: 'ಬಿನ್‌ಗೆ', priceBreakdown: 'ಬೆಲೆ ವಿವರ', estimatedPrice: 'ಅಂದಾಜು ಬೆಲೆ', deliveryFee: 'ವಿತರಣಾ ಶುಲ್ಕ', deliveryEarning: 'ನಿಮ್ಮ ಆದಾಯ', noPayments: 'ಇನ್ನೂ ಪಾವತಿಗಳಿಲ್ಲ' },
  subscription: { title: 'ಚಂದಾ', myPlans: 'ನನ್ನ ಯೋಜನೆಗಳು', newSubscription: 'ಹೊಸ ಚಂದಾ', createSubscription: 'ನಿಯಮಿತ ಪಿಕಪ್ ಹೊಂದಿಸಿ', daily: 'ದೈನಿಕ ಸಂಗ್ರಹ', dailyDesc: 'ಪ್ರತಿದಿನ ಪಿಕಪ್', alternate: 'ಪರ್ಯಾಯ ದಿನಗಳು', weekly: 'ವಾರಕ್ಕೊಮ್ಮೆ', biweekly: 'ಎರಡು ವಾರಕ್ಕೊಮ್ಮೆ', perPickup: 'ಪಿಕಪ್‌ಗೆ', perMonth: 'ತಿಂಗಳಿಗೆ', monthlyEstimate: 'ಮಾಸಿಕ ಅಂದಾಜು', monthlySavings: 'ಮಾಸಿಕ ಉಳಿತಾಯ', discountedPrice: 'ರಿಯಾಯಿತಿ ಬೆಲೆ', discount: 'ರಿಯಾಯಿತಿ', active: 'ಸಕ್ರಿಯ', paused: 'ವಿರಾಮ', cancelled: 'ರದ್ದು', pause: 'ವಿರಾಮ', resume: 'ಮುಂದುವರಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', dailyCollection: 'ದೈನಿಕ ಸಂಗ್ರಹ', requestToday: 'ಇಂದು ವಿನಂತಿಸಿ' },
  analytics: { title: 'ವಿಶ್ಲೇಷಣೆ', wasteRequestsTrend: 'ತ್ಯಾಜ್ಯ ವಿನಂತಿ ಪ್ರವೃತ್ತಿ', wasteTypeDistribution: 'ತ್ಯಾಜ್ಯ ಪ್ರಕಾರ ವಿತರಣೆ', monthlySpending: 'ಮಾಸಿಕ ಖರ್ಚು', earningsTrend: 'ಆದಾಯ ಪ್ರವೃತ್ತಿ', pickupStatus: 'ಪಿಕಪ್ ಸ್ಥಿತಿ', orderStatus: 'ಆರ್ಡರ್ ಸ್ಥಿತಿ', deliveryStatus: 'ವಿತರಣಾ ಸ್ಥಿತಿ', noData: 'ಪ್ರದರ್ಶಿಸಲು ಡೇಟಾ ಇಲ್ಲ' },
  productJourney: { title: 'ಉತ್ಪನ್ನ ಪ್ರಯಾಣ', wasteGenerated: 'ತ್ಯಾಜ್ಯ ಉತ್ಪತ್ತಿ', requestCreated: 'ವಿನಂತಿ ರಚಿಸಲಾಗಿದೆ', manufacturerAccepted: 'ತಯಾರಕರು ಸ್ವೀಕರಿಸಿದರು', transportAssigned: 'ಸಾರಿಗೆ ನಿಯೋಜಿಸಲಾಗಿದೆ', pickedUp: 'ಎತ್ತಿಕೊಂಡರು', deliveredToManufacturer: 'ತಯಾರಕರಿಗೆ ವಿತರಿಸಲಾಗಿದೆ', received: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ', processing: 'ಸಂಸ್ಕರಣೆ', finishedProduct: 'ಸಿದ್ಧ ಉತ್ಪನ್ನ', productListed: 'ಉತ್ಪನ್ನ ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ', completed: 'ಪೂರ್ಣ', trackProduct: 'ಉತ್ಪನ್ನ ಪ್ರಯಾಣ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ' },
  theme: { light: 'ಲೈಟ್ ಮೋಡ್', dark: 'ಡಾರ್ಕ್ ಮೋಡ್', switchToDark: 'ಡಾರ್ಕ್ ಮೋಡ್‌ಗೆ ಬದಲಿಸಿ', switchToLight: 'ಲೈಟ್ ಮೋಡ್‌ಗೆ ಬದಲಿಸಿ' }
};
