export const ml = {
  app: { name: 'തുളിർ', tagline: 'മാലിന്യത്തിന് അപ്പുറമുള്ള ഒരു ഭാവി സൃഷ്ടിക്കുന്നു', subtitle: 'തുളിർ ഇന്ന് മാലിന്യങ്ങൾ കൈകാര്യം ചെയ്യുക മാത്രമല്ല ചെയ്യുന്നത്; മാലിന്യങ്ങൾ ഉപയോഗപ്രദമായ വിഭവങ്ങളായും മൂല്യമായും സുസ്ഥിര അവസരങ്ങളായും മാറ്റപ്പെടുന്ന ഒരു ഭാവി നിർമ്മിക്കുകയാണ്.' },
  nav: { home: 'ഹോം', howItWorks: 'എങ്ങനെ പ്രവർത്തിക്കുന്നു', about: 'ഞങ്ങളെ കുറിച്ച്', marketplace: 'മാർക്കറ്റ്', login: 'ലോഗിൻ', getStarted: 'ആരംഭിക്കൂ', dashboard: 'ഡാഷ്ബോർഡ്', logout: 'ലോഗൗട്ട്', language: 'ഭാഷ' },
  hero: { cta: 'മാലിന്യ പിക്കപ്പ് അഭ്യർത്ഥന', ctaSecondary: 'മാർക്കറ്റ് കാണൂ' },
  ecosystem: { title: 'ഞങ്ങളുടെ ആവാസവ്യവസ്ഥ', subtitle: 'മാലിന്യത്തിൽ നിന്ന് മൂല്യത്തിലേക്കുള്ള പൂർണ്ണ വൃത്താകാര യാത്ര', waste: 'മാലിന്യം', collect: 'ശേഖരിക്കൂ', verify: 'പരിശോധിക്കൂ', manufacture: 'നിർമ്മിക്കൂ', create: 'സൃഷ്ടിക്കൂ', deliver: 'വിതരണം ചെയ്യൂ', reuse: 'പുനരുപയോഗം' },
  roles: { title: 'ആറ് ബന്ധിത പങ്കാളിത്തങ്ങൾ', subtitle: 'ഓരോ പങ്കാളിത്തവും വൃത്താകാര സമ്പദ്‌വ്യവസ്ഥയിൽ നിർണായക പങ്ക് വഹിക്കുന്നു', wasteGenerator: 'മാലിന്യ ഉൽപ്പാദകൻ', collectionPartner: 'ശേഖരണ പങ്കാളി', manufacturer: 'നിർമ്മാതാവ്', consumer: 'ഉപഭോക്താവ്', deliveryPartner: 'വിതരണ പങ്കാളി', admin: 'അഡ്മിൻ', wasteGeneratorDesc: 'മാലിന്യം ഉത്തരവാദിത്തത്തോടെ നിർമ്മാർജ്ജനം ചെയ്യാൻ ആഗ്രഹിക്കുന്ന വീടുകൾ, ഹോട്ടലുകൾ, ഭക്ഷണശാലകൾ.', collectionPartnerDesc: 'ഉൽപ്പാദകരിൽ നിന്ന് മാലിന്യം ശേഖരിച്ച് നിർമ്മാതാക്കൾക്ക് എത്തിക്കുന്ന പങ്കാളികൾ.', manufacturerDesc: 'ശേഖരിച്ച മാലിന്യത്തെ മൂല്യവത്തായ ഉൽപ്പന്നങ്ങളാക്കി മാറ്റുന്ന സ്ഥാപനങ്ങൾ.', consumerDesc: 'പുനചംക്രമണ മാലിന്യത്തിൽ നിന്ന് നിർമ്മിച്ച പരിസ്ഥിതി സൗഹൃദ ഉൽപ്പന്നങ്ങൾ വാങ്ങുന്ന വാങ്ങുന്നവർ.', deliveryPartnerDesc: 'നിർമ്മാതാക്കളിൽ നിന്ന് ഉപഭോക്താക്കൾക്ക് തയ്യാറായ ഉൽപ്പന്നങ്ങൾ എത്തിക്കുന്ന ലോജിസ്റ്റിക്സ് പങ്കാളികൾ.', adminDesc: 'മുഴുവൻ ആവാസവ്യവസ്ഥയും നിരീക്ഷിക്കുകയും നിയന്ത്രിക്കുകയും ചെയ്യുന്ന പ്ലാറ്റ്ഫോം അഡ്മിനിസ്ട്രേറ്റർമാർ.' },
  auth: { login: 'ലോഗിൻ', signup: 'സൈൻ അപ്പ്', email: 'ഇമെയിൽ', password: 'പാസ്‌വേഡ്', confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കൂ', fullName: 'മുഴുവൻ പേര്', phone: 'ഫോൺ നമ്പർ', location: 'സ്ഥലം', role: 'പങ്ക്', forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?', createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കൂ', alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?', dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?', welcomeBack: 'തിരികെ സ്വാഗതം', welcomeMessage: 'നിങ്ങളുടെ തുളിർ അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യൂ', signupMessage: 'ഇന്ന് വൃത്താകാര സമ്പദ്‌വ്യവസ്ഥയിൽ ചേരൂ', resetPassword: 'പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യൂ', resetPasswordMessage: 'പാസ്‌വേഡ് റീസെറ്റ് ലിങ്ക് ലഭിക്കാൻ നിങ്ങളുടെ ഇമെയിൽ നൽകൂ', sendResetLink: 'റീസെറ്റ് ലിങ്ക് അയയ്ക്കൂ', backToLogin: 'ലോഗിനിലേക്ക് മടങ്ങൂ' },
  waste: { createRequest: 'മാലിന്യ അഭ്യർത്ഥന സൃഷ്ടിക്കൂ', myRequests: 'എന്റെ അഭ്യർത്ഥനകൾ', wasteType: 'മാലിന്യ തരം', weight: 'ഭാരം (കിഗ്രാ)', estimatedQuantity: 'കണക്കാക്കിയ അളവ്', numberOfBags: 'ബാഗുകൾ/ബിന്നുകൾ എണ്ണം', pickupLocation: 'പിക്കപ്പ് സ്ഥലം', pickupDate: 'പിക്കപ്പ് തീയതി', pickupTime: 'പിക്കപ്പ് സമയം', additionalNotes: 'അധിക കുറിപ്പുകൾ', types: { organic: 'ജൈവ', foodWaste: 'ഭക്ഷ്യ മാലിന്യം', plastic: 'പ്ലാസ്റ്റിക്', paper: 'കടലാസ്', cardboard: 'കാർഡ്ബോർഡ്', glass: 'ഗ്ലാസ്', metal: 'ലോഹം', eWaste: 'ഇ-മാലിന്യം', mixed: 'മിശ്രിത', other: 'മറ്റുള്ളവ' }, weightMessage: 'കൃത്യമായ ഭാരം അറിയില്ലേ? സാരമില്ല. ശേഖരണ പങ്കാളി പിക്കപ്പ് സമയത്ത് പരിശോധിക്കും.', status: { requested: 'അഭ്യർത്ഥിച്ചു', accepted: 'സ്വീകരിച്ചു', onTheWay: 'വഴിയിൽ', arrived: 'എത്തി', collected: 'ശേഖരിച്ചു', inTransit: 'നിർമ്മാതാവിലേക്ക് ഗതാഗതത്തിൽ', delivered: 'നിർമ്മാതാവിന് വിതരണം ചെയ്തു' } },
  common: { loading: 'ലോഡ് ചെയ്യുന്നു...', error: 'എന്തോ തെറ്റ് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കൂ.', success: 'വിജയം!', save: 'സേവ്', cancel: 'റദ്ദാക്കൂ', delete: 'ഇല്ലാതാക്കൂ', edit: 'എഡിറ്റ്', view: 'കാണൂ', submit: 'സമർപ്പിക്കൂ', accept: 'സ്വീകരിക്കൂ', reject: 'നിരസിക്കൂ', confirm: 'സ്ഥിരീകരിക്കൂ', noData: 'ഡാറ്റ ലഭ്യമല്ല', back: 'പിന്നിലേക്ക്', next: 'അടുത്തത്', previous: 'മുമ്പത്തേത്', close: 'അടയ്ക്കൂ', refresh: 'പുതുക്കൂ', locationUnavailable: 'ലൊക്കേഷൻ ആക്സസ് ലഭ്യമല്ല. ബ്രൗസറിൽ ലൊക്കേഷൻ അനുമതി പ്രവർത്തനക്ഷമമാക്കൂ.', requiredField: 'ഈ ഫീൽഡ് ആവശ്യമാണ്', invalidEmail: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകൂ', passwordMismatch: 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല', passwordTooShort: 'പാസ്‌വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ ആയിരിക്കണം', invalidPhone: 'സാധുവായ ഫോൺ നമ്പർ നൽകൂ', invalidWeight: 'സാധുവായ ഭാരം നൽകൂ', invalidPrice: 'സാധുവായ വില നൽകൂ', invalidQuantity: 'സാധുവായ അളവ് നൽകൂ' },
  notifications: { title: 'അറിയിപ്പുകൾ', markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തൂ', noNotifications: 'ഇതുവരെ അറിയിപ്പുകൾ ഇല്ല' },
  footer: { tagline: 'ബന്ധിത വൃത്താകാര സമ്പദ്‌വ്യവസ്ഥയിലൂടെ മാലിന്യത്തെ മൂല്യമാക്കി മാറ്റുന്നു.', platform: 'പ്ലാറ്റ്ഫോം', resources: 'വിഭവങ്ങൾ', legal: 'നിയമ', contact: 'ഞങ്ങളെ ബന്ധപ്പെടൂ', privacy: 'സ്വകാര്യതാ നയം', terms: 'സേവന നിബന്ധനകൾ', faq: 'പതിവ് ചോദ്യങ്ങൾ', support: 'പിന്തുണ', copyright: '© 2026 തുളിർ. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.' },
  finance: { earnings: 'വരുമാനം', payments: 'പേയ്‌മെന്റുകൾ', payouts: 'പേഔട്ട്', totalEarnings: 'ആകെ വരുമാനം', pendingPayout: 'ശേഷിക്കുന്ന പേഔട്ട്', paidOut: 'നൽകിയത്', commission: 'കമ്മീഷൻ', platformCommission: 'പ്ലാറ്റ്ഫോം കമ്മീഷൻ', baseFee: 'അടിസ്ഥാന ഫീസ്', distanceCharge: 'ദൂര ചാർജ്', perKm: 'കി.മീ-ന്', totalPayable: 'ആകെ അടയ്ക്കേണ്ട തുക', estimatedTotal: 'എസ്റ്റിമേറ്റ് ചെയ്ത ആകെ', wasteCharge: 'മാലിന്യ ചാർജ്', basePickup: 'അടിസ്ഥാന പിക്കപ്പ് ചാർജ്', distanceByTransport: 'ട്രാൻസ്പോർട്ട് കണക്കാക്കും', paymentId: 'പേയ്‌മെന്റ് ഐഡി', paymentStatus: 'പേയ്‌മെന്റ് സ്ഥിതി', payoutStatus: 'പേഔട്ട് സ്ഥിതി', paid: 'നൽകി', pending: 'ശേഷിക്കുന്നു', rateCard: 'നിരക്ക് കാർഡ്', perBin: 'ബിന്നിന്', priceBreakdown: 'വില വിശദാംശം', estimatedPrice: 'എസ്റ്റിമേറ്റ് വില', deliveryFee: 'ഡെലിവറി ഫീസ്', deliveryEarning: 'നിങ്ങളുടെ വരുമാനം', noPayments: 'ഇതുവരെ പേയ്‌മെന്റുകൾ ഇല്ല' },
  subscription: { title: 'സബ്‌സ്ക്രിപ്ഷൻ', myPlans: 'എന്റെ പ്ലാനുകൾ', newSubscription: 'പുതിയ സബ്‌സ്ക്രിപ്ഷൻ', createSubscription: 'ആവർത്തന പിക്കപ്പ് സജ്ജമാക്കൂ', createDesc: 'സബ്‌സ്‌ക്രൈബ് ചെയ്ത് മുൻകൂർ വിശദാംശങ്ങളോടും കിഴിവ് നിരക്കുകളോടും കൂടി പിക്കപ്പുകൾ വേഗത്തിൽ സൃഷ്ടിക്കൂ.', collectionPlan: 'ശേഖരണ പ്ലാൻ', daily: 'ദൈനംദിന ശേഖരണം', dailyDesc: 'എല്ലാ ദിവസവും പിക്കപ്പ്', alternate: 'ഇതര ദിവസങ്ങൾ', alternateDesc: 'ഓരോ 2 ദിവസവും പിക്കപ്പ്', weekly: 'ആഴ്ചതോറും', weeklyDesc: 'ആഴ്ചയിൽ ഒരിക്കൽ പിക്കപ്പ്', biweekly: 'രണ്ടാഴ്ചതോറും', biweeklyDesc: 'ഓരോ 2 ആഴ്ചയും പിക്കപ്പ്', save: 'സേവ്', perPickup: 'പിക്കപ്പിന്', perMonth: 'മാസത്തിന്', pickupsPerMonth: 'പിക്കപ്പുകൾ/മാസം', monthlyEstimate: 'മാസ എസ്റ്റിമേറ്റ്', monthlySavings: 'മാസ സേവിംഗ്‌സ്', discountedPrice: 'കിഴിവ് വില', originalPrice: 'യഥാർത്ഥ വില', discount: 'കിഴിവ്', active: 'സജീവം', paused: 'താൽക്കാലികമായി നിർത്തി', cancelled: 'റദ്ദാക്കി', pause: 'നിർത്തൂ', resume: 'തുടരൂ', cancel: 'റദ്ദാക്കൂ', noSubscriptions: 'ഇതുവരെ സബ്‌സ്ക്രിപ്ഷനുകൾ ഇല്ല', startSubscription: 'സബ്‌സ്ക്രിപ്ഷൻ ആരംഭിക്കൂ', dailyCollection: 'ദൈനംദിന ശേഖരണം', requestToday: 'ഇന്ന് അഭ്യർത്ഥിക്കൂ', subscriptionSummary: 'സബ്‌സ്ക്രിപ്ഷൻ സംഗ്രഹം' },
  analytics: { title: 'അനലിറ്റിക്സ്', wasteRequestsTrend: 'മാലിന്യ അഭ്യർത്ഥന ട്രെൻഡ്', wasteTypeDistribution: 'മാലിന്യ തരം വിതരണം', monthlySpending: 'മാസ ചെലവ്', requestStatus: 'അഭ്യർത്ഥന സ്ഥിതി', wasteReceivedTrend: 'ലഭിച്ച മാലിന്യ ട്രെൻഡ്', earningsTrend: 'വരുമാന ട്രെൻഡ്', wasteTypeReceived: 'ലഭിച്ച മാലിന്യ തരം', pickupStatus: 'പിക്കപ്പ് സ്ഥിതി', completedPickupsTrend: 'പൂർത്തിയായ പിക്കപ്പ് ട്രെൻഡ്', spendingTrend: 'ചെലവ് ട്രെൻഡ്', orderStatus: 'ഓർഡർ സ്ഥിതി', ordersByMonth: 'മാസം തിരിച്ചുള്ള ഓർഡറുകൾ', deliveryStatus: 'ഡെലിവറി സ്ഥിതി', completedDeliveriesTrend: 'പൂർത്തിയായ ഡെലിവറി ട്രെൻഡ്', paymentsTrend: 'പേയ്‌മെന്റ് ട്രെൻഡ്', productSales: 'ഉൽപ്പന്ന വിൽപ്പന', usersByRole: 'റോൾ അനുസരിച്ച് ഉപയോക്താക്കൾ', noData: 'ഡാറ്റ ലഭ്യമല്ല' },
  productJourney: { title: 'ഉൽപ്പന്ന യാത്ര', wasteGenerated: 'മാലിന്യം ഉത്പാദിപ്പിച്ചു', requestCreated: 'അഭ്യർത്ഥന സൃഷ്ടിച്ചു', manufacturerAccepted: 'നിർമ്മാതാവ് സ്വീകരിച്ചു', transportAssigned: 'ഗതാഗതം നിയോഗിച്ചു', pickedUp: 'എടുത്തു', deliveredToManufacturer: 'നിർമ്മാതാവിന് നൽകി', received: 'ലഭിച്ചു', processing: 'പ്രോസസ്സിംഗ്', finishedProduct: 'പൂർത്തിയായ ഉൽപ്പന്നം', productListed: 'ഉൽപ്പന്നം ലിസ്റ്റ് ചെയ്തു', consumerPurchased: 'ഉപഭോക്താവ് വാങ്ങി', orderProcessed: 'ഓർഡർ പ്രോസസ്സ് ചെയ്തു', deliveredToConsumer: 'ഉപഭോക്താവിന് നൽകി', completed: 'പൂർത്തിയായി', trackProduct: 'ഉൽപ്പന്ന യാത്ര ട്രാക്ക് ചെയ്യൂ' },
  theme: { light: 'ലൈറ്റ് മോഡ്', dark: 'ഡാർക്ക് മോഡ്', switchToDark: 'ഡാർക്ക് മോഡിലേക്ക് മാറൂ', switchToLight: 'ലൈറ്റ് മോഡിലേക്ക് മാറൂ' }
};
