export const te = {
  app: { name: 'తుళిర్', tagline: 'వ్యర్థాలకు అతీతంగా భవిష్యత్తును సృష్టించడం', subtitle: 'తుళిర్ ఈరోజు వ్యర్థాలను నిర్వహించడం మాత్రమే కాదు; వ్యర్థాలు ఉపయోగకరమైన వనరులు, విలువ మరియు స్థిరమైన అవకాశాలుగా మారే భవిష్యత్తును నిర్మిస్తోంది.' },
  nav: { home: 'హోమ్', howItWorks: 'ఎలా పనిచేస్తుంది', about: 'గురించి', marketplace: 'మార్కెట్', login: 'లాగిన్', getStarted: 'ప్రారంభించండి', dashboard: 'డాష్‌బోర్డ్', logout: 'లాగ్అవుట్', language: 'భాష' },
  hero: { cta: 'వ్యర్థ పికప్ అభ్యర్థన', ctaSecondary: 'మార్కెట్‌ని అన్వేషించండి' },
  ecosystem: { title: 'మా పర్యావరణ వ్యవస్థ', subtitle: 'వ్యర్థం నుండి విలువకు పూర్తి వృత్తాకార ప్రయాణం', waste: 'వ్యర్థం', collect: 'సేకరణ', verify: 'ధృవీకరణ', manufacture: 'తయారీ', create: 'సృష్టించు', deliver: 'అందజేయి', reuse: 'పునర్వినియోగం' },
  roles: { title: 'ఆరు అనుసంధాన పాత్రలు', subtitle: 'ప్రతి పాత్ర వృత్తాకార ఆర్థిక వ్యవస్థలో కీలక భాగం', wasteGenerator: 'వ్యర్థ ఉత్పత్తిదారు', collectionPartner: 'సేకరణ భాగస్వామి', manufacturer: 'తయారీదారు', consumer: 'వినియోగదారు', deliveryPartner: 'డెలివరీ భాగస్వామి', admin: 'అడ్మిన్' },
  auth: { login: 'లాగిన్', signup: 'సైన్ అప్', email: 'ఇమెయిల్', password: 'పాస్‌వర్డ్', confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి', fullName: 'పూర్తి పేరు', phone: 'ఫోన్ నంబర్', location: 'స్థానం', role: 'పాత్ర', forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?', createAccount: 'ఖాతా సృష్టించండి', welcomeBack: 'తిరిగి స్వాగతం', welcomeMessage: 'మీ తుళిర్ ఖాతాలో సైన్ ఇన్ చేయండి' },
  waste: { createRequest: 'వ్యర్థ అభ్యర్థన సృష్టించండి', myRequests: 'నా అభ్యర్థనలు', wasteType: 'వ్యర్థ రకం', weight: 'బరువు (కేజీ)', types: { organic: 'జైవిక', foodWaste: 'ఆహార వ్యర్థం', plastic: 'ప్లాస్టిక్', paper: 'కాగితం', cardboard: 'కార్డ్‌బోర్డ్', glass: 'గాజు', metal: 'లోహం', eWaste: 'ఇ-వ్యర్థం', mixed: 'మిశ్రమం', other: 'ఇతర' }, weightMessage: 'ఖచ్చితమైన బరువు తెలియదా? ఫరవాలేదు. మా సేకరణ భాగస్వామి పికప్ సమయంలో ధృవీకరిస్తారు.' },
  common: { loading: 'లోడ్ అవుతోంది...', error: 'ఏదో తప్పు జరిగింది. దయచేసి మళ్ళీ ప్రయత్నించండి.', success: 'విజయం!', save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', edit: 'సవరించు', view: 'చూడు', submit: 'సమర్పించు', accept: 'అంగీకరించు', reject: 'తిరస్కరించు', confirm: 'నిర్ధారించు', noData: 'డేటా అందుబాటులో లేదు', back: 'వెనుకకు', next: 'తదుపరి', close: 'మూసివేయి', locationUnavailable: 'లొకేషన్ యాక్సెస్ అందుబాటులో లేదు. దయచేసి మీ బ్రౌజర్‌లో లొకేషన్ అనుమతిని ఎనేబుల్ చేయండి.' },
  notifications: { title: 'నోటిఫికేషన్‌లు', markAllRead: 'అన్నీ చదివినట్లు గుర్తించు', noNotifications: 'ఇంకా నోటిఫికేషన్‌లు లేవు' },
  footer: { copyright: '© 2026 తుళిర్. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.' },
  finance: { earnings: 'ఆదాయం', payments: 'చెల్లింపులు', payouts: 'పేఔట్', totalEarnings: 'మొత్తం ఆదాయం', pendingPayout: 'పెండింగ్ పేఔట్', paidOut: 'చెల్లించబడింది', commission: 'కమీషన్', platformCommission: 'ప్లాట్‌ఫారం కమీషన్', baseFee: 'ప్రాథమిక రుసుము', distanceCharge: 'దూర ఛార్జ్', perKm: 'కి.మీ-కి', totalPayable: 'మొత్తం చెల్లించాల్సిన మొత్తం', estimatedTotal: 'అంచనా మొత్తం', wasteCharge: 'వ్యర్థ ఛార్జ్', basePickup: 'ప్రాథమిక పికప్ ఛార్జ్', distanceByTransport: 'ట్రాన్స్‌పోర్ట్ లెక్కిస్తుంది', paymentId: 'చెల్లింపు ఐడీ', paymentStatus: 'చెల్లింపు స్థితి', payoutStatus: 'పేఔట్ స్థితి', paid: 'చెల్లించబడింది', pending: 'పెండింగ్', rateCard: 'రేట్ కార్డ్', perBin: 'బిన్‌కి', priceBreakdown: 'ధర వివరాలు', estimatedPrice: 'అంచనా ధర', deliveryFee: 'డెలివరీ ఫీ', deliveryEarning: 'మీ ఆదాయం', noPayments: 'ఇంకా చెల్లింపులు లేవు' },
  subscription: { title: 'సబ్‌స్క్రిప్షన్', myPlans: 'నా ప్లాన్‌లు', newSubscription: 'కొత్త సబ్‌స్క్రిప్షన్', createSubscription: 'రెగ్యులర్ పికప్ సెటప్ చేయండి', daily: 'రోజువారీ సేకరణ', dailyDesc: 'ప్రతిరోజూ పికప్', alternate: 'ప్రత్యామ్నాయ రోజులు', weekly: 'వారంవారీ', biweekly: 'ద్వి-వారం', perPickup: 'పికప్‌కి', perMonth: 'నెలకు', monthlyEstimate: 'నెలవారీ అంచనా', monthlySavings: 'నెలవారీ పొదుపు', discountedPrice: 'తగ్గింపు ధర', discount: 'తగ్గింపు', active: 'యాక్టివ్', paused: 'పాజ్ చేయబడింది', cancelled: 'రద్దు', pause: 'పాజ్', resume: 'కొనసాగించు', cancel: 'రద్దు చేయి', dailyCollection: 'రోజువారీ సేకరణ', requestToday: 'ఈరోజు అభ్యర్థించండి' },
  analytics: { title: 'అనలిటిక్స్', wasteRequestsTrend: 'వ్యర్థ అభ్యర్థన ట్రెండ్', wasteTypeDistribution: 'వ్యర్థ రకం పంపిణీ', monthlySpending: 'నెలవారీ ఖర్చు', earningsTrend: 'ఆదాయ ట్రెండ్', pickupStatus: 'పికప్ స్థితి', orderStatus: 'ఆర్డర్ స్థితి', deliveryStatus: 'డెలివరీ స్థితి', noData: 'ప్రదర్శించడానికి డేటా లేదు' },
  productJourney: { title: 'ఉత్పత్తి ప్రయాణం', wasteGenerated: 'వ్యర్థం ఉత్పత్తి అయింది', requestCreated: 'అభ్యర్థన సృష్టించబడింది', manufacturerAccepted: 'తయారీదారు అంగీకరించారు', transportAssigned: 'రవాణా కేటాయించబడింది', pickedUp: 'ఎత్తుకున్నారు', deliveredToManufacturer: 'తయారీదారుకు అందజేయబడింది', received: 'అందుకున్నారు', processing: 'ప్రాసెసింగ్', finishedProduct: 'పూర్తయిన ఉత్పత్తి', productListed: 'ఉత్పత్తి జాబితా చేయబడింది', completed: 'పూర్తయింది', trackProduct: 'ఉత్పత్తి ప్రయాణం ట్రాక్ చేయండి' },
  theme: { light: 'లైట్ మోడ్', dark: 'డార్క్ మోడ్', switchToDark: 'డార్క్ మోడ్‌కు మారండి', switchToLight: 'లైట్ మోడ్‌కు మారండి' }
};
